### ISSUE TITLE
breaking change on Python 3.10

### ISSUE THREAD

**Issue by maxadamo** [privtext/privtext-python#3]
this error below might be caused by a change that was introduced to Python 3.10:  https://bugs.python.org/issue40943

p.s.: I moved to `docopt` a while ago :wink: 

This is the output of the error:
```
Traceback (most recent call last):
  File "/usr/bin/privtext", line 9, in <module>
    sys.exit(main.run(sys.argv[1:]))
  File "/usr/local/lib/python3.10/dist-packages/privtext/__main__.py", line 53, in run
    private.send()
  File "/usr/local/lib/python3.10/dist-packages/privtext/__init__.py", line 366, in send
    self._makeprivate(self.text)
  File "/usr/local/lib/python3.10/dist-packages/privtext/__init__.py", line 101, in _makeprivate
    note, secure_key = self._encryptNote(text)
  File "/usr/local/lib/python3.10/dist-packages/privtext/__init__.py", line 227, in _encryptNote
    crpt = AES.new(key, AES.MODE_CBC, iv)
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

**Comment by maxadamo** [comment]
any chance to get this fixed?
